language: java
jdk:
- openjdk7
env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  matrix:
  - DB=mysql TASK=travis:backend:test
  - TASK=dist
before_script:
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar);
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
- 'export JAVA_OPTS="-Xmx1G $JAVA_OPTS"'
- git clone --branch v1.4.5-nyudev01 https://github.com/NYULibraries/archivesspace.git 
- ln -s $PWD archivesspace/plugins
- echo "AppConfig[:plugins] << 'nyu_marcxml_export_plugin' " > archivesspace/common/config/config.rb
- cp build.xml archivesspace/build
branches:
  except:
  - gh-pages
script:
- archivesspace/build/run $TASK $TASK_OPTS
sudo: false
